# Generated by Django 4.1.7 on 2023-02-23 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0002_rename_userextend_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
