# Generated by Django 4.1.7 on 2023-03-03 12:44

from django.db import migrations, models
import django.db.models.deletion
import librarian.models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0005_book_delete_addbook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=10)),
                ('student_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReturnBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
            ],
        ),
        migrations.CreateModel(
            name='IssueBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField(auto_now=True)),
                ('expiry_date', models.DateField(default=librarian.models.expiry)),
                ('book_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.book')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='librarian.student')),
            ],
        ),
    ]
