# Generated by Django 4.1.7 on 2023-03-28 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0006_student_returnbook_issuebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='book_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='issuebook',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50),
        ),
    ]
