# Generated by Django 4.1.7 on 2023-03-28 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarian', '0007_alter_book_book_id_alter_issuebook_book_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='returnbook',
            name='book_id',
            field=models.CharField(max_length=50),
        ),
    ]
